### ISSUE TITLE
Cannot send transactions over 1,000 888 via GUI Wallet

### ISSUE THREAD

**Issue by fedaykinofdune** [octocoin/octocoin#1]
When filling in the amount to send box, it automatically adds a comma to the amount, thus making it impossible to send more than 999.99 coins at a time, unless you use the debug window or command line. For instance, typing in 3800 888 into the box and clicking "Send" or pressing Enter will automatically insert the comma and make the number 3,800, then will turn red upon trying to send, no error message or anything. Had to send via debug window!

**Comment by octocoin** [comment]
The originally posted "1.8 preview" OctoCoin Windows-QT client had this bug - we added visual styling based on the selected locale to improve the display and reduce the chance of input errors. While the styling was stripped in the submit function, the actual frontend was causing this bug. The version of the Windows-QT client posted 5/24 and onward has this functionality removed and, therefore, has no issues.
